- README.md
- docker-compose.yml
- with_rvm.dockerfile
- without_rvm.dockerfile
Closes https://snapsheettech.atlassian.net/browse/SRE-726
*NOTE: There is a separate known issue with the current Tinker Homebrew formula. This PR is introducing a way to test and develop formulae without corrupting the developers localhost configuration.*
> Error: Calling GitHub.open_api is disabled! Use GitHub::API.open_rest instead.
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:17:in `open_api'
By using `docker-compose`, we can create an isolated container that behaves like an end-user environment when installing formulae and testing their development.
Currently, developing Homebrew formulae is inconsistent. Differences in local development environments can lead to different results for different users.
Clone this repository if you don't have it already, and …
> SRE-726 Improved Homebrew Formula Debugging

- Dockerfile
- Formula/tinker.rb
- README.md
- lib/debug_tools.rb
- lib/ruby_gems_download_strategy.rb
- lib/ruby_manager.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1055
Builds were passing when we tested them via docker compose using Linux, but the process that was used for installation on Linux did not align properly with MacOS. This fixes installations for both operating systems by creating an isolated version of Ruby that won't overlap with any existing installation of Ruby. It uses RVM to achieve this (see code documentation comments).
A new module that can be shared between formulas and download strategies for enabling `binding.pry` breakpoints when attempting to install a formula with `--debug`.
This manages the building and installation of a dedicated version of Ruby using RVM. This requires that the user has RVM installed, and that RVM is installed using the single-user method, which is …
> SRE-1055 rvm: command not found

- lib/debug_tools.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1080
Fixes issue when installing tinker homebrew formula using --debug.
This gets rid of the error seen on docker contain and the 11.6.2 specific macOS version
Removes the specific line in the `setup_debug_tools` method that causes the issue.
First reproduce the error on the `main` branch of this project by running the following:
```
docker compose build
docker compose run --rm cli
brew install --debug --build-from-source Formula/tinker.rb
brew install --debug --build-from-source Formula/tinker.rb
```
The install will fail during the second install.
Now pull down these changes and run the following.
Build and start the docker container
```
docker compose build
docker compose run --rm cli
```
Then download the Tinker …
> SRE-1080 Error: cannot load such file -- interception

- Formula/tinker.rb
- docker-compose.yml
Closes https://snapsheettech.atlassian.net/browse/SRE-1117
This addresses a dependency issue that occurs when the local version of awscli conflicts with the version of awscli that Tinker depends upon.
We specify `awscli` version 2 as a [Homebrew dependency](https://docs.brew.sh/Formula-Cookbook#specifying-other-formulae-as-dependencies). When installed, Homebrew will explicitly include the library in the PATH that we write within the wrapper entrypoint for Tinker. This ensures the brew-installed version will take priority, without requiring the user to modify their PATH via .profile/.bashrc/.zshrc/etc.
Checkout this branch, rebuild the dev image, and start a container. This will mount the `~/.aws` directory and enable you to test `tinker auth`.
```
git checkout …
```
> SRE-1117 Error: Default profile needs to be set

- Formula/session-manager-plugin.rb
- Formula/session_manager_plugin.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1147
This introduces a new formula for installing the `session-manager-plugin` for both Linux and macOS. This will be included as a dependency of the Tinker formula in a follow-up change.
Checkout this branch:
```shell
git checkout jSRE_1147-update-homebrew-formula-depend
```
Make sure you don't have the Cask version installed.
```shell
brew remove session-manager-plugin
```
Install the commands.
```shell
brew install awscli jq
brew install --build-from-source Formula/session-manager-plugin.rb
```
Verify the brew test works.
```shell
brew test session-manager-plugin
```
Verify which version 
```shell
which session-manager-plugin
session-manager-plugin --version
```
Comment out this line in your .profile/.bashrc/.zshrc file.
Open a new …
> SRE-1147 Create Session Manager Plugin Formula

- Formula/session-manager-plugin.rb
- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1169
This includes the recently published session-manager-plugin formula as a dependency in the Tinker Homebrew formula.
While testing, I discovered that the SHA has changed for macos version of the plugin.
```shell
Error: tinker: SHA256 mismatch
Expected: 67e527dd19b2ae6d5b5de62c75aedb4241f31b2ae177be3e118db8b4d067ad26
Actual: dad3eb15607c675d20ddc8a4b199c46d458b70ed6188afb7c83fb1a1d7a44911
File: /Users/david.tittle/Library/Caches/Homebrew/downloads/456d9d21168cf84a91f8ac096612ada4ed42c61c569a92a2516ce0281c06dfa2--session-manager-plugin.pkg
```
This only occurred while testing the installation on macOS.
Checkout this branch, start a container, and run the installer:
```shell
➜  homebrew-core git:(main) git checkout …
```
> SRE-1169 Include Session Manager Plugin Dependency in Tinker Formula

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1185
Updating Homebrew to use the newest version of Tinker - 0.2.3
> SRE-1185 Update Homebrew Formula for Release 0.2.3

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1201
Update tinker formula to install version 0.3.1
Checkout this branch and remove existing installation:
```
git checkout jSRE_1201-update-homebrew-formula-for-re
```
Run the install:
```
brew test Formula/tinker.rb # Ensure test throws no error
```
Run sample Tinker commands to confirm that tinker works as expected:
```shell
tinker --version # Should return 0.3.1
LOG_LEVEL=trace tinker console
tinker tf imports --config infra/deploy-testing.yaml --json | jq
```
Remove this test version installed.
> SRE-1201 Update Homebrew Formula for Release 0.3.1

- Formula/session-manager-plugin.rb
Only changes MacOS:
Remove any existing versions so they don't interfere with testing:
```
brew remove tinker session-manager-plugin
brew update
```
Because of the SHA difference, download the session-manager-plugin from the formula reference first:
```
brew install --build-from-source Formula/session-manager-plugin.rb
```
Reinstall Tinker with the local formula
```
```
This will take several minutes. Confirm the installation is successful and that the proper versions are installed:
```
tinker --version 
> 0.3.1
```
```
/usr/local/bin/session-manager-plugin --version
> 1.2.295.0
```
After you are done testing, you can uninstall 
```
brew remove tinker session-manager-plugin
```
> SRE_1212 updating session manger plugin to work for all macOS

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1213
Currently users are not able to download Tinker without running `brew install cmake` first. This update adds `cmake`  a dependency in the homebrew formula so users will not have to run `brew install cmake` before downloading Tinker.
Uninstall Tinker
```
```
Uninstall cmake if you have it downloaded already
```
brew uninstall cmake
```
Install Tinker (not from this branch)
```
```
You should see the following error:
```
Last 15 lines from /Users/deena.tenzer/Library/Logs/Homebrew/tinker/02.gem:
--srcdir=.
--curdir
--ruby=/usr/local/Cellar/tinker/0.3.1/.rvm/rubies/ruby-2.7.1/bin/$(RUBY_BASE_NAME)
--with-sha1dc
--without-sha1dc
--use-system-libraries
To see why this extension …
```
> SRE_1213 adding cmake to dependencies

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1244
Update the Tinker version number and checksum to version 0.4.1
```shell
git remote update --prune && git checkout jSRE_1244-update-homebrew-to-install-tin
```
Remove tinker from your local.
```
```
Run the installer on macOS
```
```
Confirm the version was installed
```
```
0.4.1
Uninstall this version and reinstall the current version of Tinker:
```shell
```
0.4.0
> SRE-1244: Update tinker to 0.4.1

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1263
Update the Tinker version number and checksum to version 0.5.0
```shell
git remote update --prune && git checkout jSRE_1263-update-tinker-formula-for-vers
```
Remove tinker from your local.
```
```
Run the installer on macOS
```
```
Confirm the version was installed
```
```
0.5.0
Uninstall this version and reinstall the current version of Tinker:
```shell
```
0.4.1
> SRE-1263: Update Tinker to 0.5.0

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1371
This releases Tinker version 0.5.1
Remove tinker on your local.
```
```
Checkout this branch and install Tinker using the script.
```
git checkout jSRE_1371-update-tinker-formula-for-vers
```
Verify the correct tinker version.
```
0.5.1
```
Verify that the help messages for the `tinker tf` subcommands (like `tinker tf help imports`) looks as expected.
```
Usage:
tinker tf imports
Options:
--config=CONFIG
[--environment=ENVIRONMENT]
[--json], [--no-json]
[--profile=PROFILE]
[--project=PROJECT]
[--region=REGION]
-v, [--verbose], [--no-verbose]
Render a list of key-value pairs representing already existing resources.
```
Verify that `tinker tf …
> SRE-1371 Update Tinker Formula for Version 0.5.1

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1392
Remove tinker on your local.
```
```
Checkout this branch and install Tinker using the script.
```
git checkout jSRE_1392-update-tinker-formula-for-vers
```
Verify the correct tinker version.
```
0.5.2
```
Remove the testing version and reinstall the released version.
```
```
> SRE_1392 updating version and sha to 0.5.2

- Formula/tinker.rb
- README.md
Closes https://snapsheettech.atlassian.net/browse/SRE-1441
**NOTE**: Recently Homebrew updated to [version 3.6.0](https://brew.sh/2022/09/07/homebrew-3.6.0/). Since this upgrade I ran into issues when installing session-manager-plugin as a dependency of a locally-run formula. I've confirmed that the existing dependency on the remote formula (Github/here) still works. You will also confirm this as the last step.
Make sure homebrew is up to date:
```shell
brew update && brew upgrade
```
Remove your local version of tinker and session-manager-plugin:
```shell
brew remove session-manager-plugin
```
You must also explicitly remove the snapsheet/core tap:
```shell
```
Check out this branch:
```shell
git checkout …
```
> SRE-1441 Update Tinker Homebrew Formula to 0.5.3

- Formula/tinker.rb
- lib/ruby_manager.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1451
Publish Tinker version 0.5.4
Make sure homebrew is up to date:
```shell
brew update && brew upgrade
```
Remove your local version of tinker and session-manager-plugin:
```shell
brew remove session-manager-plugin
```
You must also explicitly remove the snapsheet/core tap:
```shell
```
Check out this branch:
```shell
git checkout jSRE_1451-update-tinker-homebrew-formula
```
Open `Formula/tinker.rb` in a text editor and comment-out this line:
```ruby
#depends_on "snapsheet/core/session-manager-plugin" => "1.2.295"
```
Run brew install with the formula. This will take several minutes.
```shell
brew install --formula --build-from-source Formula/tinker.rb
```
Confirm that you have the latest …
> SRE-1451 Update Tinker Homebrew Formula to 0.5.4

- Formula/tinker.rb
- README.md
Closes https://snapsheettech.atlassian.net/browse/SRE-1684
Bump release version and SHA.
Ensure you have your Github token set as HOMEBREW_GITHUB_API_TOKEN in your CLI. If you are using the GitHub CLI with SSO, you can do it with the following commands:
```shell
gh auth login --scopes read:packages
HOMEBREW_GITHUB_API_TOKEN=$(gh auth token)
```
Run the following
```
brew install --formula --build-from-source Formula/tinker.rb
```
Verify that thinker installs version 0.5.5 correctly.
```
0.5.5
```
When installing the `snapsheet/core/session-manager-plugin` dependency listed in the local version of the script, brew was raising an unusual error `Error: can't modify frozen class`. Since we do not yet use this as a dependency, I've removed it to unblock …
> SRE-1684 - Release Tinker 0.5.5

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1770
Bump release version and SHA.
Ensure you have your Github token set as HOMEBREW_GITHUB_API_TOKEN in your CLI. If you are using the GitHub CLI with SSO, you can do it with the following commands:
```shell
gh auth login --scopes read:packages
HOMEBREW_GITHUB_API_TOKEN=$(gh auth token)
```
Remove the current Tinker first:
```
brew remove snapsheet/core/tinker
```
Then run the following
```
brew install --formula --build-from-source Formula/tinker.rb
```
Verify that thinker installs version 0.5.6 correctly.
```
0.5.6
```
> SRE_1739 updating to new tinker 0.5.6

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1774
Bump release version and SHA.
Ensure you have your Github token set as HOMEBREW_GITHUB_API_TOKEN in your CLI. If you are using the GitHub CLI with SSO, you can do it with the following commands:
```shell
gh auth login --scopes read:packages
HOMEBREW_GITHUB_API_TOKEN=$(gh auth token)
```
Remove the current Tinker first:
```
brew remove snapsheet/core/tinker
```
Then run the following
```
brew install --formula --build-from-source Formula/tinker.rb
```
Verify that thinker installs version 0.5.6 correctly.
```
0.6.1
```
> SRE_1774 updating to tinker 0.6.1

- lib/ruby_gems_download_strategy.rb
Fixing Homebrew breaking change:
Check out this branch. 
```
brew remove tinker && brew untap snapsheet/core
```
OR Update locally cached file instead of using this PR:
```
brew remove tinker && brew untap snapsheet/core
HOMEBREW_GITHUB_API_TOKEN=$(gh auth token) brew install snapsheet/core/tinker
open /opt/homebrew/Library/Taps/snapsheet/homebrew-core/lib/ruby_gems_download_strategy.rb
HOMEBREW_GITHUB_API_TOKEN=$(gh auth token) brew install snapsheet/core/tinker
```
Confirm tinker version 
```
✔tinker --version
> 0.6.1
```
If you see the following error when running `tinker --version`
```
✔ tinker --version
/Users/deena.tenzer/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3 …
```
> SRE-1787 updating params

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1790
Check out this branch and run the following
```
brew remove tinker && brew untap snapsheet/core
```
Confirm tinker version 
```
✔tinker --version
> 0.7.1
```
> SRE_1790 updating tinker version to 0.7.1

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1820
Check out this branch and run the following
```
brew remove tinker && brew untap snapsheet/core
```
Confirm tinker version 
```
✔tinker --version
> 0.7.2
```
> SRE_1820 Updating tinker version 0.7.2 and SHA

- Formula/tinker.rb
Relates to https://snapsheettech.atlassian.net/browse/SRE-2032
```shell
```
```shell
```
```shell
1.0.0
```
> Release Tinker 1.0

- Formula/tinker.rb
```shell
```
```shell
```
```shell
1.0.1
```
```shell
❯ tinker run -p guidelines -e production -r us-east-1 ls -lah
⠇ Task[fb534c75d4cb459e897fde9a119ed699](RUNNING) ExecuteCommandAgent(RUNNING) 
The Session Manager plugin was installed successfully. Use the AWS CLI to start a session.
```
Uninstall this version and reinstall the official version:
```shell
brew uninstall …
```
> Tinker Patch 1.0.1

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-2118
Homebrew upgraded to ruby 3 and we need to update our formula so that it works with the new version.
Jacob notice the following an error while updating tinker. 
```
jake@KQVPM7HPQT ~ % brew install snapsheet/core/tinker  
==> Fetching snapsheet/core/tinker
==> Fetching tinker gem from GitHub packages.
Downloaded tinker-1.0.1
==> Installing tinker from snapsheet/core
Error: An exception occurred within a child process:
Psych::DisallowedClass: Tried to load unspecified class: Gem::Specification
jake@KQVPM7HPQT ~ % 
```
Load the metadata using [Gem::Package library](https://docs.ruby-lang.org/en/master/Gem/Package.html). 
Uninstall tinker using 
```
brew uninstall session-manager-plugin …
```
> SRE-2118-homebrew-tinker-download-failing

- Formula/tinker.rb
```shell
```
```shell
```
```shell
1.0.2
```
```shell
❯ sail tinker run -p snapsheet-tx --environment uat --region us-east-1 rails c
⠇ Task[fb534c75d4cb459e897fde9a119ed699](RUNNING) ExecuteCommandAgent(RUNNING) 
The Session Manager plugin was installed successfully. Use the AWS CLI to start a session.
```
Uninstall this version and reinstall the official version:
```shell …
```
> Updating tinker version to 1.0.2

- Formula/tinker.rb
```shell
```
```shell
```
```shell
1.3.0
```
```shell
❯ tinker keys list -p snapsheet-tx --environment qa3
```
Confirm secrets are returned.
Uninstall this version and reinstall the official version:
```shell
HOMEBREW_GITHUB_API_TOKEN=$(gh auth token) brew install snapsheet/core/tinker
```
> Updating tinker 1.3.0

- Formula/tinker.rb
```shell
```
```shell
```
```shell
1.3.1
```
```shell
❯ tinker keys set -p api-gateway -e qa1 TEST_KEY=test_val
```
Confirm secrets are set and [resources](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/api-gateway-qa1/services?region=us-east-2) are updated properly.
Remove secret:
```shell
❯ tinker keys remove -p api-gateway -e qa1 TEST_KEY
```
Uninstall this …
> updating to tinker 1.3.1

- Formula/tinker.rb
```shell
```
```shell
```
```shell
1.3.2
```
```shell
❯ tinker keys set -p vice-backend -e qa1 TEST_KEY=test_val
```
Confirm [secrets](https://us-east-2.console.aws.amazon.com/secretsmanager/secret?name=vice-backend-qa1&region=us-east-2) are set and [resources](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/awseb-9b2e-qa1-qmvqmtbmc9/services?region=us-east-2) are …
> Updating tinker 1.3.2 version and sha

- Formula/tinker.rb
```shell
```
```shell
```
```shell
1.3.4
```
Run tinker session command to validate expected behavior.
```shell
❯ tinker session list -p vice-backend -e uat-1 -r us-east-1
```
Confirm this returns either a table with the session information or `No remote session tasks currently running.`
I saw an error when downloading this new version
```
Error: /opt/homebrew/bin/gh is too old, you must upgrade it to continue
```
This is …
> Updating tinker version and SHA

- Formula/tinker.rb
```shell
```
```shell
```
```shell
1.3.5
```
Run tinker session command to validate expected behavior.
```shell
❯ tinker deploy -e qa5 -r us-east-2 -p vice-backend --tag 9b2e-qa5__e0d5fa8bb2__2024-07-11_070602
```
Confirm this runs with no errors or timeouts. This confirms that the task definitions are being created properly with and without tags. This also confirms timeouts do not occur.
Run a build. Navigate into the …
> Updating tinker version to 1.3.5

- Formula/tinker.rb
Updates the version number and SHA for the next release of Tinker.
```shell
```
```shell
```
```shell
1.3.6
```
Run a deployment to QA6
``` shell
tinker deploy -e qa6 -r us-east-2 -p vice-backend --tag 9b2e-qa6__9f4c625e93__2024-08-15_223501
```
Once the deployment is complete, run the following and confirm there are no errors running the session
```shell
tinker run -e qa6 -p vice-backend -r us-east-2 bash
```
> updating to tinker 1.3.6

- Formula/tinker.rb
Updates the version number and SHA for the next release of Tinker.
```shell
```
```shell
```
```shell
1.3.7
```
> Updating tinker 1.3.7

- Formula/tinker.rb
Updates the version number and SHA for the next release of Tinker.
```shell
```
```shell
```
```shell
1.3.9
```
> Updating tinker to 1.3.9

- Formula/tinker.rb
Updates the version number and SHA for the next release of Tinker.
```shell
```
```shell
```
```shell
1.4.0
```
> Updating tinker 1.4.0
