- with_rvm.dockerfile
- without_rvm.dockerfile
Closes https://snapsheettech.atlassian.net/browse/SRE-1044
This fixes the issues seen when trying to test formulae via the containers provided by docker-compose.
Confirm that the images can be built:
```
docker compose build
```
Open a terminal with one of the dev containers:
```
docker compose run --rm test_without_rvm
```
Update brew and install a package:
```
brew update && brew install sl
```
Run the package you installed:
```
sl
```
Open a terminal with the RVM container:
```
docker compose run --rm test_with_rvm
```
Run RVM commands and see that the environment is as expected:
```
rvm list
which ruby
irb
```
> SRE-1044 Fix Docker Dev Environment

- Dockerfile
- Formula/tinker.rb
- README.md
- lib/debug_tools.rb
- lib/ruby_gems_download_strategy.rb
- lib/ruby_manager.rb
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/13222/tab/release-report-all-issues
> Release 1.0.1

- Formula/tinker.rb
- docker-compose.yml
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/13388/tab/release-report-all-issues
> Release 1.0.2

- Formula/session-manager-plugin.rb
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/13480/tab/release-report-all-issues
> Release 1.0.3

- Formula/tinker.rb
Release https://snapsheettech.atlassian.net/projects/SRE/versions/13568/tab/release-report-all-issues
> Release 1.0.5

- Formula/tinker.rb
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/13605/tab/release-report-all-issues
> Release 1.0.6

- Formula/tinker.rb
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/13611/tab/release-report-all-issues
> Release 1.0.7

- Formula/session-manager-plugin.rb
Release: https://snapsheettech.atlassian.net/projects/SRE/versions/13622/tab/release-report-all-issues
> Release 1.0.8

- Formula/tinker.rb
Release https://snapsheettech.atlassian.net/projects/SRE/versions/13641/tab/release-report-all-issues
> Release 1.0.9

- Formula/tinker.rb
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/13704/tab/release-report-all-issues
> Release 1.0.11 

- Formula/tinker.rb
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/13754/tab/release-report-all-issues
> SRE-1263: Update Tinker to 0.5.0 (#30)

- Formula/tinker.rb
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/13948/tab/release-report-all-issues
> Release 1.0.13

- Formula/tinker.rb
Closes https://snapsheettech.atlassian.net/browse/SRE-1392
Remove tinker on your local.
```
```
Checkout this branch and install Tinker using the script.
```
git checkout jSRE_1392-update-tinker-formula-for-vers
```
Verify the correct tinker version.
```
0.5.2
```
Remove the testing version and reinstall the released version.
```
```
> SRE_1392 updating version

- Formula/tinker.rb
- README.md
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/14088/tab/release-report-all-issues
> Release 1.0.15

- Formula/tinker.rb
- lib/ruby_manager.rb
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/14105/tab/release-report-all-issues
> Release 1.0.16

- Formula/tinker.rb
- README.md
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/14670/tab/release-report-all-issues
> Release 1.1

- Formula/tinker.rb
Release: https://snapsheettech.atlassian.net/projects/SRE/versions/15021/tab/release-report-all-issues
> SRE_1770 updating to new tinker 0.5.6 (#44)

- Formula/tinker.rb
Release: https://snapsheettech.atlassian.net/projects/SRE/versions/15031/tab/release-report-all-issues
> SRE_1771 Updating Tinker version to 0.6.0 (#46)

- Formula/tinker.rb
Release: https://snapsheettech.atlassian.net/projects/SRE/versions/15037/tab/release-report-all-issues
> SRE_1774 Tinker 0.6.1

- lib/ruby_gems_download_strategy.rb
Fixing homebrew breaking change: https://github.com/Homebrew/brew/pull/15257
Release: https://snapsheettech.atlassian.net/projects/SRE/versions/15094/tab/release-report-all-issues
> SRE-1787 Homebrew Breaking Change Fix

- Formula/tinker.rb
Release: https://snapsheettech.atlassian.net/projects/SRE/versions/15067/tab/release-report-all-issues
> Release 1.3

- lib/ruby_gems_download_strategy.rb
Releases https://snapsheettech.atlassian.net/projects/SRE/versions/15236/tab/release-report-all-issues
> Release 1.5

- Formula/tinker.rb
> Release 1.6
